title: Phi-Markets 
iconURL: assets/phi-md.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: sbarriac14
  github: elpollazo

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
theme: jekyll-theme-leaf
